### ISSUE TITLE
Reading 2+ channels

### ISSUE THREAD

**Issue by willfaulds** [baruch/ADS1115#1]
I love the speed/simplicity of this library but cannot work out how to read 2+ channels...?

**Comment by pavellzubkov** [comment]
**Reading all 4 channels**
I use [AsyncDelay](https://github.com/stevemarple/AsyncDelay) lib for async timer

```
#include "AsyncDelay.h"
#include "ADS1115.h"

struct AdcMeas
{ 
  long ain0; // long because i use 32bit controller and send struct over
  long ain1; //
  long ain2; //
  long ain3; //
};

AsyncDelay measADCTimer;
AsyncDelay sendADCTimer;
ADS1115 adc(0x48);
AdcMeas adc_res;
ads1115_mux adc_inp;

void adcsetup()
{
    adc_inp = ADS1115_MUX_GND_AIN0;
    adc.begin();
    adc.set_data_rate(ADS1115_DATA_RATE_860_SPS);
    adc.set_mode(ADS1115_MODE_CONTINUOUS);
    adc.set_mux(adc_inp);
    adc.set_pga(ADS1115_PGA_TWO);

    if (adc.trigger_sample() != 0)
        Serial.println("adc read trigger failed (ads1115 not connected?)");

    measADCTimer.start(5, AsyncDelay::MILLIS);
    sendADCTimer.start(50, AsyncDelay::MILLIS);
}

void adcloop()
{
    char sDebug[128];
    if (measADCTimer.isExpired())
    {
        switch (adc_inp)
        {
        case ADS1115_MUX_GND_AIN0:
            adc_res.ain0 = adc.read_sample();
            adc_inp = ADS1115_MUX_GND_AIN1;
            break;
        case ADS1115_MUX_GND_AIN1:
            adc_res.ain1 = adc.read_sample();
            adc_inp = ADS1115_MUX_GND_AIN2;
            break;
        case ADS1115_MUX_GND_AIN2:
            adc_res.ain2 = adc.read_sample();
            adc_inp = ADS1115_MUX_GND_AIN3;            
            break;
        case ADS1115_MUX_GND_AIN3:
            adc_res.ain3 = adc.read_sample();
            adc_inp = ADS1115_MUX_GND_AIN0;            
            break;
        }
        adc.set_mux(adc_inp);
        adc.trigger_sample();
        measADCTimer.repeat();
    }

    if (sendADCTimer.isExpired())
    {
        //ws_sendMessage(&adc_res);
        sprintf(sDebug, "ain0 - %d ain1 - %d ain2 - %d ain3 - %d\n\r", adc_res.ain0, adc_res.ain1, adc_res.ain2, adc_res.ain3);
        Serial.print(sDebug);
        sendADCTimer.repeat();
    }
}
```

**Comment by baruch** [comment]
With the logic that you have you are first reading AIN0 and only then triggering the sample, that would obviously not work. Also, you are setting the continuous mode where you actually want single shot for each timer.

It's been a while since I written and used this library but it is pretty much a straight through implementation of the API of the chip so you should read the chip spec and see how to best use it for your needs.

For what you want you can have the main timer at 50msec as you already do and then set the other one to be once every  2msecs in that polling timer you need a state machine similar to what you have but you need a first state that says you need to request the first pin, and issue a request on that, switch to waiting for pin 1 and then wait until the !adc.is_sample_in_progress() and then you can read the data, initiate a poll for pin2 and change state to wait for pin 2 until you are done.

**Comment by pavellzubkov** [comment]
thanks you for lib. 
it works. i use it with esp8266. 
ofcourse we can use other logic but it works too.) chip start read ain0. after 5 ms i read result ain0, change input to ain1 and start reading. after 5ms read result ain1 ....
i not need single shot in my case
